### ISSUE TITLE
history

### ISSUE THREAD

**Issue by jcblw** [honeinc/viewmanager#1]
seems a shame to blowout the history on this.

**Comment by andyburke** [comment]
didn't really mean to blow out the history, figured it was different enough that ymir would continue. Probably should have forked it but will add a reference to the readme.

**Comment by andyburke** [comment]
didn't really mean to blow out the history, figured it was different enough that ymir would continue. Probably should have forked it but will add a reference to the readme.

**Comment by andyburke** [comment]
didn't really mean to blow out the history, figured it was different enough that ymir would continue. Probably should have forked it but will add a reference to the readme.
